# Generated by Django 3.0.6 on 2020-05-23 12:28

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bubbleworld', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='postpart',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
