# Generated by Django 3.0.6 on 2020-05-25 07:23

import bubbleworld.models
import ckeditor.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bubbleworld', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='dislike_number',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='like_number',
        ),
        migrations.AddField(
            model_name='comment',
            name='dislike_user',
            field=models.ManyToManyField(blank=True, related_name='dislike_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='like_user',
            field=models.ManyToManyField(blank=True, related_name='like_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='star',
            field=bubbleworld.models.IntegerRangeField(default=3, verbose_name='评分'),
        ),
    ]
