# Generated by Django 3.0.6 on 2020-05-18 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bubbleworld', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='ip_address',
        ),
    ]
