# Generated by Django 3.0.6 on 2020-05-25 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bubbleworld', '0002_auto_20200525_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='dislike_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='like_number',
            field=models.IntegerField(default=0),
        ),
    ]
