# Generated by Django 3.0.6 on 2020-05-18 13:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bubbleworld', '0003_auto_20200518_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='black_list',
            field=models.ManyToManyField(blank=True, related_name='_user_black_list_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='follow_to',
            field=models.ManyToManyField(blank=True, related_name='_user_follow_to_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
