# Generated by Django 3.0.6 on 2020-05-25 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bubbleworld', '0003_auto_20200525_1643'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentreport',
            old_name='reason',
            new_name='content',
        ),
    ]
