# Generated by Django 3.0.6 on 2020-05-25 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bubbleworld', '0004_auto_20200525_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='postpart',
            name='type_postpart',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='postpartcomment',
            name='type_postpartcomment',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='commentreport',
            name='content',
            field=models.TextField(verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='commentreport',
            name='title',
            field=models.CharField(max_length=40, verbose_name='标题'),
        ),
    ]
