# Generated by Django 3.0.6 on 2020-05-18 13:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bubbleworld', '0004_auto_20200518_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='section',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
