# Generated by Django 3.0.6 on 2020-05-26 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bubbleworld', '0005_auto_20200525_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='postpart',
            name='content_number',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='AdminApply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adminapply_section', to='bubbleworld.Section')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adminapply_author', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '管理员申请',
                'verbose_name_plural': '管理员申请',
                'db_table': 'adminapply',
                'ordering': ['-created_at'],
            },
        ),
    ]
