# Generated by Django 3.0.6 on 2020-05-20 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bubbleworld', '0006_auto_20200520_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='img',
            field=models.CharField(default='/static/open-iconic/png/person-3x.png', max_length=200, verbose_name='图标'),
        ),
    ]
