# Generated by Django 3.0.6 on 2020-05-26 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bubbleworld', '0006_auto_20200526_2001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='notice',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='notice',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='notice',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='section',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='user',
            name='black_list',
        ),
        migrations.RemoveField(
            model_name='user',
            name='follow_to',
        ),
        migrations.DeleteModel(
            name='Follow',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Notice',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
