# Generated by Django 3.0.6 on 2020-05-20 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bubbleworld', '0007_auto_20200520_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.CharField(default='/static/open-iconic/png/person-3x.png', max_length=200, verbose_name='头像'),
        ),
    ]
