# Generated by Django 3.0.6 on 2020-05-21 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bubbleworld', '0008_auto_20200520_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='section_type',
            field=models.IntegerField(default=0),
        ),
    ]
