# Generated by Django 3.0.6 on 2020-05-22 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bubbleworld', '0009_section_section_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='img',
            field=models.CharField(default='/static/img/book/白夜行.jpg', max_length=200, verbose_name='图标'),
        ),
    ]
